# Generated by Django 5.2.5 on 2025-09-24 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Visit'), ('login', 'Login'), ('map_view', 'Map View'), ('report_create', 'Report Create'), ('stats_reflected', 'Stats Reflected')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='metrics_eve_event_t_cd1539_idx'), models.Index(fields=['user', 'created_at'], name='metrics_eve_user_id_0362d9_idx')],
            },
        ),
    ]
