# Generated by Django 5.2.5 on 2025-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='event',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
