# Generated by Django 5.2.5 on 2025-09-04 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('계정', '계정'), ('결제', '결제'), ('신고/제보', '신고/제보'), ('버그', '버그'), ('기능요청', '기능요청'), ('기타', '기타')], default='기타', max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('answered', 'answered'), ('closed', 'closed'), ('deleted', 'deleted')], default='open', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_msg_at', models.DateTimeField(blank=True, null=True)),
                ('last_admin_msg_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('system', 'system')], max_length=10)),
                ('body', models.TextField()),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inquiries.inquiry')),
                ('sender_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_messages_sent_as_admin', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_messages_sent_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='inquiries_i_user_id_608dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirymessage',
            index=models.Index(fields=['inquiry', 'created_at'], name='inquiries_i_inquiry_65da5c_idx'),
        ),
    ]
