# Generated by Django 5.2.3 on 2025-07-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
            ],
        ),
    ]
