# Generated by Django 5.2.5 on 2025-08-27 04:39

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedplace',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='savedplace',
            name='api_savedpl_user_id_c7f773_idx',
        ),
        migrations.AddField(
            model_name='savedplace',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('user', 'client_id'), name='uniq_user_client_id'),
        ),
    ]
