# Generated by Django 5.2.3 on 2025-07-27 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='english',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='features',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='precautions',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
