# Generated by Django 5.2.5 on 2025-08-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_savedplace_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedplace',
            name='uniq_user_client_id',
        ),
        migrations.AddConstraint(
            model_name='savedplace',
            constraint=models.UniqueConstraint(fields=('user', 'client_id'), name='uniq_user_client_id'),
        ),
    ]
