# Generated by Django 5.2.5 on 2025-08-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_savedplace_uniq_user_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notif_user_null_only_for_group',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status_change',
            field=models.CharField(blank=True, choices=[('checking->on_hold', '접수 완료 → 보류'), ('checking->completed', '접수 완료 → 답변 완료'), ('on_hold->completed', '보류 → 답변 완료')], db_index=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('group', '그룹 알림'), ('individual', '개별 알림')], db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'individual'), ('user__isnull', False)), models.Q(('type', 'individual'), _negated=True), _connector='OR'), name='notif_individual_requires_user'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'group'), ('user__isnull', True)), models.Q(('type', 'group'), _negated=True), _connector='OR'), name='notif_group_requires_no_user'),
        ),
    ]
