# Generated by Django 5.2.3 on 2025-08-05 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_animal_features_alter_animal_precautions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_unit', models.CharField(choices=[('year', 'year'), ('month', 'month')], max_length=10)),
                ('state_year', models.IntegerField()),
                ('state_month', models.IntegerField(default=0)),
                ('all_reports', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('incomplete', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistic',
                'ordering': ['-state_year', '-state_month'],
            },
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animal'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at'], 'verbose_name': 'SearchHistory', 'verbose_name_plural': 'SearchHistory'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change', models.CharField(max_length=50)),
                ('reply', models.TextField()),
                ('type', models.CharField(choices=[('individual', 'individual'), ('group', 'group')], max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('checking', '접수 완료'), ('on_hold', '보류'), ('completed', '답변 완료')], default='접수 완료', max_length=20)),
                ('report_region', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.animal')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('feedback_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.report')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-feedback_datetime'],
            },
        ),
    ]
