# Generated by Django 5.2.3 on 2025-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location_statistic_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_region',
        ),
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('checking', '접수 완료'), ('on_hold', '보류'), ('completed', '답변 완료')], db_index=True, default='checking', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_date'], name='api_report_report__650dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'report_date'], name='api_report_status_8ffab2_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['address', 'report_date'], name='api_report_address_dd56f8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['animal', 'report_date'], name='api_report_animal__22b3de_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'report_date'], name='api_report_user_id_ff8308_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['latitude', 'longitude'], name='api_report_latitud_8d12b4_idx'),
        ),
    ]
