# Generated by Django 5.2.5 on 2025-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_notification_notif_user_null_only_for_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name_kor',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
