# Generated by Django 5.2.3 on 2025-08-09 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_options_remove_notification_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-feedback_datetime']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['report', 'user', 'feedback_datetime'], name='api_feedbac_report__07495d_idx'),
        ),
    ]
