# Generated by Django 5.2.5 on 2025-08-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.report'),
        ),
    ]
