# Generated by Django 5.2.3 on 2025-08-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_location_options_location_animal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='region',
        ),
    ]
