# Generated by Django 5.2.5 on 2025-09-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_report_user_location_unique_location_lat_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_kor', models.CharField(max_length=50)),
                ('name_eng', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AddField(
            model_name='animal',
            name='aliases_eng',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='animal',
            name='code',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='api.animalgroup'),
        ),
    ]
