# Generated by Django 5.2.3 on 2025-08-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_address_location_region'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='api_locatio_report__b4d0fc_idx',
        ),
        migrations.RemoveField(
            model_name='location',
            name='animal',
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['report', 'user'], name='api_locatio_report__ffcd38_idx'),
        ),
    ]
