# Generated by Django 5.2.5 on 2025-09-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_animalgroup_alter_animal_options_animal_aliases_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
