# Generated by Django 5.2.3 on 2025-08-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_location_api_locatio_report__b4d0fc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='api_report_address_dd56f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='api_report_latitud_8d12b4_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.report'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('checking', '접수 완료'), ('on_hold', '보류'), ('completed', '답변 완료')], default='checking', max_length=20),
        ),
    ]
