# Generated by Django 5.2.3 on 2025-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_report_api_report_address_dd56f8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='api_locatio_report__ffcd38_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city', 'district'], name='api_locatio_city_40d0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='api_locatio_latitud_670fa5_idx'),
        ),
    ]
