# Generated by Django 5.2.3 on 2025-08-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_location_api_locatio_report__ffcd38_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.location'),
        ),
    ]
