# Generated by Django 5.2.5 on 2025-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_devicetoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'keyword'], name='api_searchh_user_id_35fbf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchhistory',
            constraint=models.UniqueConstraint(fields=('user', 'keyword'), name='uniq_searchhistory_user_keyword'),
        ),
    ]
