# Generated by Django 5.2.5 on 2025-10-01 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_searchhistory_api_searchh_user_id_35fbf6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('cta_url', models.CharField(blank=True, default='', max_length=300)),
                ('audience', models.CharField(default='all', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-id'],
            },
        ),
    ]
