# Generated by Django 5.2.5 on 2025-10-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_appbanner_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
