# Generated by Django 5.2.5 on 2025-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_devicetoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
