# Generated by Django 5.2.5 on 2025-11-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_devicetoken_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('target', models.CharField(default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='NoticeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'success'), ('failure', 'failure')], max_length=20)),
                ('fcm_msg_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.devicetoken')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.notice')),
            ],
            options={
                'indexes': [models.Index(fields=['notice', 'status'], name='api_noticed_notice__3063c9_idx'), models.Index(fields=['device_token', 'status'], name='api_noticed_device__17cc9d_idx')],
                'unique_together': {('notice', 'device_token')},
            },
        ),
    ]
