# Generated by Django 5.2.5 on 2025-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_notice_devicetoken_last_seen_noticedelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_url',
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals/'),
        ),
    ]
