# Generated by Django 5.2.3 on 2025-08-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장치 이름')),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=10, verbose_name='상태')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='마지막 신호 수신 시간')),
            ],
        ),
        migrations.CreateModel(
            name='MotionSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('감지됨', '감지됨'), ('오프라인', '오프라인')], max_length=10, verbose_name='감지 상태')),
                ('detected_at', models.DateTimeField(auto_now=True, verbose_name='감지 시각')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='dashboard.cctvdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(verbose_name='신고 일시')),
                ('animal_name', models.CharField(max_length=50, verbose_name='동물 이름')),
                ('status', models.CharField(max_length=20, verbose_name='처리 상태')),
                ('report_region', models.CharField(max_length=255, verbose_name='신고 지역')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
