# Generated by Django 5.2.5 on 2025-09-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='동물명')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='신고 제목'),
        ),
        migrations.AlterField(
            model_name='report',
            name='animal_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='동물 이름(기존)'),
        ),
        migrations.AddField(
            model_name='report',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dashboard.animal'),
        ),
    ]
