# Generated by Django 5.2.5 on 2025-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_animal_report_title_alter_report_animal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_period', models.CharField(choices=[('all', '전체'), ('7d', '최근7일'), ('30d', '최근30일')], default='all', max_length=10)),
                ('default_sort', models.CharField(choices=[('newest', '최신순'), ('oldest', '오래된순')], default='newest', max_length=10)),
                ('unresolved_statuses', models.JSONField(default=list)),
                ('aging_threshold_days', models.PositiveSmallIntegerField(default=3)),
                ('notify_status_change', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(blank=True, default='', max_length=200)),
                ('map_provider', models.CharField(choices=[('kakao', 'Kakao'), ('naver', 'Naver'), ('google', 'Google')], default='kakao', max_length=10)),
                ('map_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '대시보드 설정',
                'verbose_name_plural': '대시보드 설정',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='animal_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='동물 이름'),
        ),
    ]
