# Generated by Django 5.2.5 on 2025-10-22 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0005_notification_noticedelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctvdevice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='motionsensor',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='prediction',
            name='dashboard_p_created_ad84b6_idx',
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='date_format',
            field=models.CharField(default='%Y-%m-%d %H:%M', max_length=32),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='mask_reporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='notify_desktop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='notify_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='page_size',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name='cctvdevice',
            index=models.Index(fields=['status'], name='dashboard_c_status_7ff29a_idx'),
        ),
        migrations.AddIndex(
            model_name='cctvdevice',
            index=models.Index(fields=['-last_heartbeat'], name='dashboard_c_last_he_0688c3_idx'),
        ),
        migrations.AddIndex(
            model_name='motionsensor',
            index=models.Index(fields=['status'], name='dashboard_m_status_0258a9_idx'),
        ),
        migrations.AddIndex(
            model_name='motionsensor',
            index=models.Index(fields=['-detected_at'], name='dashboard_m_detecte_32e725_idx'),
        ),
        migrations.AddIndex(
            model_name='motionsensor',
            index=models.Index(fields=['device', '-detected_at'], name='dashboard_m_device__d8d163_idx'),
        ),
        migrations.AddIndex(
            model_name='noticedelivery',
            index=models.Index(fields=['user', 'notice'], name='dashboard_n_user_id_0c81f2_idx'),
        ),
        migrations.AddIndex(
            model_name='noticedelivery',
            index=models.Index(fields=['-delivered_at'], name='dashboard_n_deliver_f0dccd_idx'),
        ),
        migrations.AddIndex(
            model_name='noticedelivery',
            index=models.Index(fields=['read_at'], name='dashboard_n_read_at_d1b380_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='dashboard_n_type_7f5d47_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='dashboard_n_status_2bed5b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='dashboard_n_created_dd91e3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['start_at', 'end_at'], name='dashboard_n_start_a_2934cf_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['-created_at'], name='dashboard_p_created_89abb6_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['source', '-created_at'], name='dashboard_p_source_89b316_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-report_date'], name='dashboard_r_report__bc9735_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='dashboard_r_status_6e311f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', '-report_date'], name='dashboard_r_user_id_b6be4d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_region'], name='dashboard_r_report__72ec23_idx'),
        ),
    ]
