# Generated by Django 5.2.5 on 2025-10-22 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_cctvdevice_options_alter_motionsensor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목 없음', max_length=200)),
                ('kind', models.CharField(blank=True, default='', max_length=50)),
                ('status_label', models.CharField(blank=True, default='임시저장', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['-updated_at'], name='dashboard_c_updated_264a1f_idx'), models.Index(fields=['kind'], name='dashboard_c_kind_b90000_idx'), models.Index(fields=['is_live'], name='dashboard_c_is_live_3d4a71_idx')],
            },
        ),
    ]
