# Generated by Django 5.2.5 on 2025-10-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvdevice',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='cctvdevice',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='cctvdevice',
            name='stream_url',
            field=models.URLField(blank=True, null=True, verbose_name='스트림 URL'),
        ),
        migrations.AddField(
            model_name='report',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dashboard.cctvdevice'),
        ),
        migrations.AddField(
            model_name='report',
            name='prob',
            field=models.FloatField(blank=True, null=True, verbose_name='신뢰도(0~1)'),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(default='app', max_length=20, verbose_name='출처'),
        ),
        migrations.AlterField(
            model_name='cctvdevice',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='장치 이름'),
        ),
        migrations.AlterField(
            model_name='cctvdevice',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='OFFLINE', max_length=10, verbose_name='상태'),
        ),
    ]
