# Generated by Django 5.2.5 on 2025-11-02 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_cctvdevice_lat_cctvdevice_lng_cctvdevice_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='auto_stale_days_to_pending',
            field=models.PositiveIntegerField(default=3, help_text='미처리 신고가 이 기간(일) 이상 경과하면 지정 상태로 변경', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='auto_stale_target_status',
            field=models.CharField(choices=[('대기', '대기'), ('처리중', '처리중'), ('보류', '보류')], default='대기', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='completed_report_retention_days',
            field=models.PositiveIntegerField(default=180, help_text='완료된 신고 보존 기간(일)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='db_backup_dir',
            field=models.CharField(default='backups', help_text='DB 백업 저장 경로(프로젝트 루트 기준/절대경로 허용)', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='db_backup_interval_hours',
            field=models.PositiveIntegerField(default=24, help_text='DB 백업 주기(시간)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='log_retention_days',
            field=models.IntegerField(choices=[(7, '7일'), (30, '30일'), (90, '90일')], default=30, help_text='애플리케이션/에러 로그 보관 기간(일)'),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='server_ping_interval_sec',
            field=models.PositiveIntegerField(default=10, help_text='대시보드-백엔드 헬스체크 주기(초)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='stats_refresh_interval_min',
            field=models.PositiveIntegerField(default=10, help_text='통계 캐시 리프레시 주기(분)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
