# Generated by Django 5.2.5 on 2025-10-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stream_url', models.URLField(help_text='예: http://<esp32-ip>:81/stream')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
